# Generated by Django 5.1.3 on 2024-12-11 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropApp', '0003_customermessage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PropApp.owner'),
            preserve_default=False,
        ),
    ]
